league_settings:
  number_of_teams: 12
  playoff_teams: 8
roster_settings:
  QB: 1
  RB: 2
  WR: 2
  TE: 1
  RB_WR: 1
  WR_TE: 1
  K: 1
  DST: 1
  DP: 2
  BE: 7
  IR: 1
analysis_settings:
  bye_week_conflict_threshold: 3
  num_trade_targets: 10
scoring_rules:
    passing_yards: 0.04
    passing_touchdowns: 6
    interceptions_thrown: -3
    rushing_yards: 0.1
    rushing_touchdowns: 6
    receiving_yards: 0.1
    receiving_touchdowns: 6
    receptions: 0.5
    2pt_conversion_pass: 2
    2pt_conversion_rush: 2
    2pt_conversion_rec: 2
    fumbles_lost: -2
    field_goals_made_0_39: 3
    field_goals_made_40_49: 4
    field_goals_made_50_59: 5
    field_goals_made_60_plus: 5
    field_goals_missed_0_39: -1
    extra_points_made: 1
    extra_points_missed: -1
    sacks: 1
    interceptions: 3
    fumbles_recovered: 3
    fumbles_forced: 1
    safeties: 3
    blocked_kicks: 2
    defensive_touchdowns: 6
    points_allowed_0: 10
    points_allowed_1_6: 7.5
    points_allowed_7_13: 5
    points_allowed_14_17: 2.5
    points_allowed_22_27: -2.5
    points_allowed_28_34: -5
    points_allowed_35_45: -7.5
    points_allowed_46_plus: -10
    total_yards_allowed_less_100: 10
    total_yards_allowed_100_199: 7.5
    total_yards_allowed_200_299: 5
    total_yards_allowed_300_349: 2.5
    total_yards_allowed_400_449: -2.5
    total_yards_allowed_450_499: -7.5
    total_yards_allowed_500_549: -15
    total_yards_allowed_550_plus: -25
    solo_tackles: 0.75
    assisted_tackles: 0.5
    passes_defensed: 1
    stuffs: 1
    kickoff_return_touchdowns: 6
    punt_return_touchdowns: 6
    40_plus_yard_td_pass_bonus: 1
    50_plus_yard_td_pass_bonus: 2
    40_plus_yard_td_rec_bonus: 1
    50_plus_yard_td_rec_bonus: 2
    40_plus_yard_td_rush_bonus: 1
    50_plus_yard_td_rush_bonus: 2
    100_199_yard_receiving_game: 3
    200_plus_yard_receiving_game: 4
    100_199_yard_rushing_game: 3
    200_plus_yard_rushing_game: 4
    300_399_yard_passing_game: 3
    400_plus_yard_passing_game: 4
    every_25_kickoff_return_yards: 0.04
    every_25_punt_return_yards: 0.04
