league_settings:
  league_name: San Cola Cup Covid Years
  number_of_teams: 12
  playoff_teams: 8
  year: 2025
  data_years:
  - 2023
  - 2024
roster_settings:
  BE: 7
  D_ST: 1
  DP: 2
  IR: 1
  K: 1
  QB: 1
  RB: 2
  RB_WR: 1
  TE: 1
  WR: 2
  WR_TE: 1
scoring_rules:
  0_points_allowed: 10.0
  1_6_points_allowed: 7.5
  1_2_sack: 0.5
  100_199_total_yards_allowed: 7.5
  100_199_yard_receiving_game: 3.0
  100_199_yard_rushing_game: 3.0
  14_17_points_allowed: 2.5
  200+_yard_receiving_game: 4.0
  200+_yard_rushing_game: 4.0
  200_299_total_yards_allowed: 5.0
  22_27_points_allowed: -2.5
  28_34_points_allowed: -5.0
  2pt_passing_conversion: 2.0
  2pt_receiving_conversion: 2.0
  2pt_return: 3.0
  2pt_rushing_conversion: 2.0
  300_349_total_yards_allowed: 2.5
  300_399_yard_passing_game: 3.0
  35_45_points_allowed: -7.5
  40+_yard_td_pass_bonus: 1.0
  40+_yard_td_rec_bonus: 1.0
  40+_yard_td_rush_bonus: 1.0
  400+_yard_passing_game: 4.0
  400_449_total_yards_allowed: -2.5
  450_499_total_yards_allowed: -7.5
  46+_points_allowed: -10.0
  50+_yard_td_pass_bonus: 2.0
  50+_yard_td_rec_bonus: 2.0
  50+_yard_td_rush_bonus: 2.0
  500_549_total_yards_allowed: -15.0
  550+_total_yards_allowed: -25.0
  7_13_points_allowed: 5.0
  assisted_tackles: 0.5
  blocked_punt_or_fg_return_for_td: 6.0
  blocked_punt,_pat_or_fg: 2.0
  each_fumble_forced: 1.0
  each_fumble_recovered: 3.0
  each_interception: 3.0
  each_pat_made: 1.0
  each_pat_missed: -1.0
  each_safety: 3.0
  every_10_receiving_yards: 1.0
  every_10_rushing_yards: 1.0
  every_25_kickoff_return_yards: 1.0
  every_25_passing_yards: 1.0
  every_25_punt_return_yards: 1.0
  every_5_receptions: 2.5
  fg_made_(0_39_yards): 3.0
  fg_made_(40_49_yards): 4.0
  fg_made_(50_59_yards): 5.0
  fg_made_(60+_yards): 5.0
  fg_missed_(0_39_yards): -1.0
  fumble_recovered_for_td: 6.0
  fumble_return_td: 6.0
  interception_return_td: 6.0
  interceptions_thrown: -3.0
  kickoff_return_td: 6.0
  less_than_100_total_yards_allowed: 10.0
  passes_defensed: 1.0
  punt_return_td: 6.0
  solo_tackles: 0.75
  stuffs: 1.0
  td_pass: 6.0
  td_reception: 6.0
  td_rush: 6.0
  total_fumbles_lost: -2.0
  total_tackles: 0.1
my_team_id: 8
llm_settings:
  provider: google
  model: gemini-2.5-flash
