---
version: '3'

vars:
  VER: '2.5'
  # GEMINI_MODEL: 'models/gemini-1.5-flash-latest'
  GEMINI_MODEL: 'models/gemini-2.5-flash'
  IMAGE: nicholaswilde/mkdocs-material
  PORT: 8000
    
tasks:
  init:
    desc: Initialize the project by creating environment file from templates.
    preconditions:
      - test -f scripts/.env.tmpl
    cmds:
      - cp scripts/.env.tmpl .env
  serve:
    desc: Serve the documentation locally using Docker.
    cmds:
      - >-
        docker run --rm -it -p {{ .PORT }}:{{ .PORT}} -v ${PWD}:/docs
        --platform linux/amd64 {{ .IMAGE }} serve
        --dev-addr 0.0.0.0:{{ .PORT }} -f ./mkdocs.yml
  export:
    desc: Export the list of available tasks to task-list.txt.
    cmds:
      - task -l > task-list.txt
  encrypt:
    desc: Encrypt secret and environment files using sops.
    preconditions:
      - test -f .env
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc
  decrypt:
    desc: Decrypt secret and environment files using sops.
    preconditions:
      - test -f .env.enc
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  gpro:
    desc: 'Run Gemini with the gemini-{{ .VER }}-pro model.'
    cmds:
      - 'gemini -m gemini-{{ .VER }}-pro'
  gflash:
    desc: Run Gemini with the gemini-2.5-flash model.
    cmds:
      - 'gemini -m gemini-{{ .VER }}-flash'
  glite:
    desc: Run Gemini with the gemini-2.5-flash-lite model.
    cmds:
      - 'gemini -m gemini-{{ .VER }}-flash-lite'
  bootstrap:
    desc: Bootstarp
    cmds:
      - python3 -m venv venv
  lint:
    desc: "Lint the code with flake8"
    cmds:
      - flake8 .
  # A task to install all the necessary Python dependencies from requirements.txt.
  deps:
    desc: Install Python dependencies
    cmds:
      - |
        source venv/bin/activate && pip install -r requirements.txt

  # A task to download the latest player stats.
  download:
    desc: "Download NFL player stats. Usage: task download -- --years 2022 2023"
    cmds:
      - python3 scripts/download_stats.py {{.CLI_ARGS}}

  # A task to have Gemini analyze your team.
  analyze:
    desc: Have Gemini analyze your team
    cmds:
      - python3 scripts/analysis.py --model {{.GEMINI_MODEL}}

  # A task to get pickup recommendations.
  pickup:
    desc: Get pickup recommendations based on available players and team needs
    cmds:
      - python3 scripts/pickup_suggester.py

  # A task to get trade suggestions.
  trade:
    desc: Get trade suggestions based on player stats
    cmds:
      - python3 scripts/trade_suggester.py

  weekly_update:
    desc: "Run the full weekly update: download stats, update team, get available players, analyze, and get suggestions."
    cmds:
      - task: download
      - task: my_team
      - task: available_players
      - task: analyze
      - task: pickup
      - task: trade

  my_team:
    desc: Get your fantasy football team and create my_team.md
    cmds:
      - python3 scripts/get_my_team.py

  available_players:
    desc: Get available players from your league and create available_players.csv
    cmds:
      - python3 scripts/get_available_players.py
      
  settings:
    desc: Get your league settings
    cmds:
      - python3 scripts/get_league_settings.py

  default:
    cmds:
      - task -l
